name: Compile-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Meng.Compile
        run: |
            cd MengJun
            gcc -c *.c

      - name: Bi.Compile
        run: |
            cd BiRan
            cd Practice1 && gcc -c *.c && cd ..
            cd Practice2 && gcc -c *.c && cd ..
            cd Practice3 && gcc -c *.c && cd ..
            cd Practice4 && gcc -c *.c && cd ..
            cd Practice5 && gcc -c *.c && cd ..
            cd Practice6 && gcc -c *.c && cd ..
